---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: image-annotator.clabs.co
webhooks:
- name: image-annotator.clabs.co
  admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVWXdIVEpGTlN1
      UzBkRGZ3V0RQL2xUMVM3VERJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RUxNQWtHQTFVRUJoTUNS
      VlV4SURBZUJnTlZCQU1NRjJsdFlXZGxMV0Z1Ym05MFlYUnZjaTEzWldKbwpiMjlyTUI0WERUSXpN
      VEF4T1RBNU1UVXhObG9YRFRJME1UQXhPREE1TVRVeE5sb3dMekVMTUFrR0ExVUVCaE1DClJWVXhJ
      REFlQmdOVkJBTU1GMmx0WVdkbExXRnVibTkwWVhSdmNpMTNaV0pvYjI5ck1JSUJJakFOQmdrcWhr
      aUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXpVeSsxOE9UUE9hWVBtcm92enhFcDZpSTJJ
      ck9KZjVJMDhEMwpoaitxRHl4QTRTclpwMEJRMy9QdlZOTk1hSU51Qi9Tc3hxdXQxU3pKRFV3ZjhB
      ZVhwVk1tYWUvQmRoRTJMdFh3CmtHSGlMQW5Cd3ZWRzR3SERoUHJYakNZcFExUjlSc0JJMmV6NEtP
      ZkRyakl6NGdrenphOXN3NW5hZUpBVTE0a1cKRGpaNDJuL3k1bG85b1hPWEJ0N0QxZzVsK3JKd0J1
      Mk1NTTdpNVhTcC9yUDd6WVRscFBTMjlmLzZkM2g4ZWlqbwpQZ0ZvOUFIYTdoM3F2cit3Z3FNWG5k
      V2dJSmxaVHpYb1ZsQTFPNlZqeStKMWJhV2JHRWx2NmpXYnpESk5wWjYrClhydzQ2T1ZLSW5kOGdu
      WS9INnpIQmVYemRtbE1BM2ViL3BZN2M4aXdBK1BNOVgrOUd3SURBUUFCbzFNd1VUQWQKQmdOVkhR
      NEVGZ1FVSzA0UUJXNk1TNTBWSkFsbm4vaGlJTHdVQ2RNd0h3WURWUjBqQkJnd0ZvQVVLMDRRQlc2
      TQpTNTBWSkFsbm4vaGlJTHdVQ2RNd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcw
      QkFRc0ZBQU9DCkFRRUFhamVBQWl5SE9obHVJd0lYdUkwLzRxb1lzNnIxYlQxZ0loU05yRWpiRmt2
      TXhtZkd0UGtCVGx0eHUyenYKZ0hNcmlHVlZlbGxLQ3J4L3JtZUQ5SGg1U1hKNzdiQ2dnT1BZdk9U
      TllwUW4xNHYwVmk1QnhKbDNBVHJWN3BVagphS3FZeVk5Uk83UGRjMFdUWXRic0VBMzBlZnBsemx2
      MDlSbGQwcjk2ZkpYMzM4SFYwdjNzdXVuRDJSSGVSRmZIClp4d1BNVlRwdW9CcUNvZnRlS2dsbFFm
      QWh2emxDMXlkNTVnWHpWZFUxckJpdit0QmFieDlNdU5JdG9EZUR2bk8KZUJldVhGVW5zTDQ5dHcy
      Tm02TWZ0TWRhQ3YxdmhmWXRFdUdWR1MzdmdOTE5aWG9NWjh2bWM5NDkwdkhsTEFCbApvendNZnpD
      WjZhOHdRVGhCZWdWUCtVQzZOdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: image-annotator-webhook
      namespace: image-annotator
      path: /mutate
      port: 8443
  # failurePolicy: Ignore
  failurePolicy: Fail
  matchPolicy: Equivalent
  namespaceSelector:
    matchExpressions:
    - key: webhooks.knative.dev/exclude
      operator: DoesNotExist
    - key: image-annotator-webhook/exclude
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: webhooks.knative.dev/exclude
      operator: DoesNotExist
    - key: image-annotator-webhook/exclude
      operator: DoesNotExist
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - pods/status
    scope: '*'
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daemonsets
    - daemonsets/status
    scope: '*'
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    - deployments/status
    scope: '*'
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicasets
    - replicasets/status
    scope: '*'
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - statefulsets
    - statefulsets/status
    scope: '*'
  - apiGroups:
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
    - cronjobs/status
    scope: '*'
  - apiGroups:
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
    - jobs/status
    scope: '*'
  - apiGroups:
    - batch
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
    - cronjobs/status
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
