---
name: CI/CD for image-annotator-webhook

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build the project
        run: |
          make build
      - name: Run the test
        run: |
          make test

  container-build-and-push-sha:
    uses: celo-org/reusable-workflows/.github/workflows/docker-build.yaml@v3.1.0-rc.4
    name: Build image-annotator-webhook image container
    needs: build-and-test
    permissions:
      actions: read
      contents: write
      pull-requests: write
      security-events: write
      attestations: write
      id-token: write
    with:
      artifact-registry: us-west1-docker.pkg.dev/devopsre/image-annotator-webhook/image-annotator-webhook
      tags: ${{ github.sha }}
      platforms: linux/amd64,linux/arm64
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-image-annotator-webhook/providers/github-by-repos
      service-account: image-annotator-webhook@devopsre.iam.gserviceaccount.com
      context: .
      file: ./Dockerfile
      trivy-enabled: false
